language: "pt-BR"

reviews:
  profile: "assertive"
  high_level_summary: false

  auto_review:
    enabled: true

    instructions: >
      FOCO PRINCIPAL: REVISÃO DE TESTES (Angular).
      Você deve priorizar e comentar PRIMEIRO sobre arquivos de teste (*.spec.ts).
      Para cada PR, faça obrigatoriamente:

      1) Se houver arquivos *.spec.ts alterados, revise-os em detalhes:
         - qualidade dos asserts (evitar toBeTruthy genérico)
         - uso correto de async/fakeAsync/tick/flush e estabilidade (flaky tests)
         - mocks/spies (mocks muito permissivos, stubs incompletos, dados irreais)
         - cobertura de cenários de erro (HTTP 4xx/5xx, throwError, timeouts)
         - edge cases (null/undefined, arrays vazios, valores fora do domínio, permissões/roles)
         - organização/clareza (arrange-act-assert, nomes, duplicação)

      2) Se houver mudanças em código de produção (component/service/etc) sem mudanças correspondentes em testes,
         aponte explicitamente que faltam testes e sugira casos de teste concretos.

      3) Sempre inclua uma seção "Test Gaps" com bullets de testes faltantes e onde adicionar.

      Formato da resposta:
      - "Revisão dos Testes (*.spec.ts)" (obrigatório)
      - "Test Gaps (o que falta cobrir)" (obrigatório)
      - "Sugestões de melhorias no código (secundário)" (opcional)