language: "pt-BR"

reviews:
  profile: "assertive"
  high_level_summary: false

  # Instruções por caminho/arquivo (forma correta no schema)
  path_instructions:
    - path: "**/*.spec.ts"
      instructions: >
        FOCO PRINCIPAL: REVISÃO DE TESTES (Angular/Jasmine/Karma ou Jest).
        Você DEVE comentar sobre arquivos *.spec.ts quando eles existirem no PR.
        Revise com profundidade:
        - qualidade dos asserts (evitar expect(x).toBeTruthy / asserts genéricos)
        - arranjo do teste (Arrange-Act-Assert), nomes e legibilidade
        - async: async/await vs fakeAsync/tick/flush, estabilidade e flakiness
        - mocks/spies: stubs incompletos, mocks permissivos demais, dados irreais
        - edge cases: null/undefined, valores fora do domínio, listas vazias
        - cenários de erro: throwError, HTTP 401/404/500, timeout/retry, fallback UI
        - cobertura de branches (caminho feliz vs erro)
        Ao final, inclua "Test Gaps" com bullets de testes faltantes.

    - path: "**/*.ts"
      instructions: >
        Para mudanças em código de produção (components/services/etc):
        - Se a mudança não vier acompanhada de testes, aponte explicitamente.
        - Sugira casos de teste concretos (cenário + arquivo .spec.ts alvo).
        Priorize sempre a testabilidade e cobertura de edge cases.

    - path: "**/*.html"
      instructions: >
        Se houver mudanças de template, sugira testes de template/DOM
        (ex.: estados loading/empty/error, botões desabilitados, *ngIf/*ngFor).

  # Auto review somente liga/desliga e filtros (sem instructions)
  auto_review:
    enabled: true