language: "pt-BR"

reviews:
  profile: "assertive"
  high_level_summary: true

  path_instructions:
    - path: "**/*.spec.ts"
      instructions: >
        REGRA: Sempre inclua um SUMÁRIO no topo do seu review (mesmo que curto).
        Em seguida, faça comentários por arquivo.

        Formato obrigatório:
        1) "Resumo (sempre)" com 3-7 bullets
        2) "Revisão por arquivo" (obrigatório)
           - Para cada arquivo *.spec.ts alterado, crie um subtítulo com o caminho do arquivo
             e liste observações específicas daquele arquivo.
        3) "Test Gaps" (obrigatório) com lista de testes faltantes e onde adicionar.

        FOCO: qualidade dos testes, edge cases, cenários de erro, flakiness, mocks.

    - path: "**/*.ts"
      instructions: >
        Se houver mudanças em código de produção sem mudanças correspondentes em testes,
        inclua no "Test Gaps" exatamente quais arquivos *.spec.ts criar/alterar e quais cenários cobrir.