language: "pt-BR"

reviews:
  profile: "assertive"
  high_level_summary: true
  request_changes_workflow: true
  high_level_summary_instructions: >-
    Always verify that any new components or services have corresponding unit tests. Identify edge cases—such as null/undefined inputs, network errors, and loading states—that are not covered in the .spec.ts files.

  path_instructions:
    - path: "**/*.spec.ts"
      instructions: >
        PRIMARY GOAL: TEST REVIEW.
        You MUST produce a clearly structured review, NOT a single generic paragraph.

        REQUIRED OUTPUT FORMAT (use Markdown headings exactly like this):
        ## Resumo (sempre)
        - (3 to 7 bullets)

        ## Revisão por arquivo (obrigatório)
        For EACH changed *.spec.ts file, add a subsection with the exact file path:
        ### Arquivo: <path>
        - Findings (specific to this file)
        - Missing assertions / weak asserts
        - Missing error-path tests
        - Edge cases not covered
        - Flakiness risks (async/fakeAsync/tick/flush), test isolation issues
        - Mocking issues (overly permissive spies, unrealistic fixtures)

        ## Test Gaps (obrigatório)
        List missing test cases as bullets in the format:
        - <path>: <scenario> — <hint how to implement>

        IMPORTANT:
        - Prefer concrete, actionable suggestions over general advice.
        - If there are no test files changed, explicitly say so and list which tests should be added.

    - path: "**/*.ts"
      instructions: >
        If production code changes are not accompanied by test changes,
        explicitly call it out under "Test Gaps" and name the target *.spec.ts files + scenarios.
        Keep production-code commentary secondary to test coverage and test quality.